sudo: false

language: python

env:
  - TOXENV=py27
  - TOXENV=py35

install:
  - python setup.py install
  - pip install -r test-requirements.txt
  - pip install tox-travis

script: tox

after_success:
  coveralls
